<?php
declare(strict_types=1);
use Yireo\HyvaCheckoutProgressBar\Magewire\Progressbar;

/** @var Progressbar $magewire */
$percentage = $magewire->getPercentage();
?>
<?= $magewire->currentCount ?> of <?= $magewire->totalCount ?>
<div class="w-full bg-gray-200 rounded-full h-1.5 mb-4 dark:bg-gray-700">
    <div class="bg-blue-600 h-1.5 rounded-full dark:bg-blue-500" style="width: <?= $percentage ?>%"></div>
</div>
