<?php
declare(strict_types=1);

use Yireo\HyvaCheckoutProgressBar\Magewire\Progressbar;

/** @var Progressbar $magewire */
?>
<div x-data="yireoHyvaCheckoutProgressBar"
     x-init="init(<?= $magewire->currentCount ?>, <?= $magewire->totalCount ?>)"
     @required-input-change.window="requiredInputChange(event)">
    <div class="w-full bg-gray-200 rounded-full h-1.5 mb-4 dark:bg-gray-700" :title="progressTitle()">
        <div class="bg-blue-600 h-2 rounded-full dark:bg-blue-500" :style="progressStyle()"></div>
    </div>
</div>
